### PR TITLE
Configure for prow

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>
Refer: kubermatic/kubermatic#11320

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by xrstf** [comment]
@hdurand0710 The webhook config was missing, I've added it now.

**Comment by hdurand0710** [comment]
Looks good now for the setting, @xrstf @mfranczy can you please /lgtm if ok ?

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
